//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTestApp.LGJTestWCFAPCECO {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.aglaia-gmbh.de/xml/BaSS_SOAPd/", ConfigurationName="LGJTestWCFAPCECO.HellaAPCECOSOAPdService")]
    public interface HellaAPCECOSOAPdService {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HellaAPCECOSOAPdServiceChannel : WinTestApp.LGJTestWCFAPCECO.HellaAPCECOSOAPdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HellaAPCECOSOAPdServiceClient : System.ServiceModel.ClientBase<WinTestApp.LGJTestWCFAPCECO.HellaAPCECOSOAPdService>, WinTestApp.LGJTestWCFAPCECO.HellaAPCECOSOAPdService {
        
        public HellaAPCECOSOAPdServiceClient() {
        }
        
        public HellaAPCECOSOAPdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HellaAPCECOSOAPdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HellaAPCECOSOAPdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HellaAPCECOSOAPdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
}
