//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudServiceHostApp.HNLYLGJ.GATE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jaxws2.vispectcloud.com/", ConfigurationName="HNLYLGJ.GATE.SmartCarCloudService")]
    public interface SmartCarCloudService {
        
        // CODEGEN: 命名空间  的元素名称 OptCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetGatherRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetGatherResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.GetGatherResponse GetGather(CloudServiceHostApp.HNLYLGJ.GATE.GetGatherRequest request);
        
        // CODEGEN: 命名空间  的元素名称 AccountID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/BindingDeviceRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/BindingDeviceResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceResponse BindingDevice(CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceRequest request);
        
        // CODEGEN: 命名空间  的元素名称 OptCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetSmartWarnRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetSmartWarnResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnResponse GetSmartWarn(CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnRequest request);
        
        // CODEGEN: 命名空间  的元素名称 SmartWarn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/SendSmartWarnRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/SendSmartWarnResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnResponse SendSmartWarn(CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnRequest request);
        
        // CODEGEN: 命名空间  的元素名称 OptCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetAgentRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetAgentResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.GetAgentResponse GetAgent(CloudServiceHostApp.HNLYLGJ.GATE.GetAgentRequest request);
        
        // CODEGEN: 命名空间  的元素名称 LoginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/RegisterAccountRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/RegisterAccountResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountResponse RegisterAccount(CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountRequest request);
        
        // CODEGEN: 命名空间  的元素名称 OptCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetAccountRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetAccountResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.GetAccountResponse GetAccount(CloudServiceHostApp.HNLYLGJ.GATE.GetAccountRequest request);
        
        // CODEGEN: 命名空间  的元素名称 LoginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/LoginCloudRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/LoginCloudResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudResponse LoginCloud(CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudRequest request);
        
        // CODEGEN: 命名空间  的元素名称 OptCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/TotalSmartWarnRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/TotalSmartWarnResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnResponse TotalSmartWarn(CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnRequest request);
        
        // CODEGEN: 命名空间  的元素名称 LoginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/AuthLoginRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/AuthLoginResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginResponse AuthLogin(CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginRequest request);
        
        // CODEGEN: 命名空间  的元素名称 CarRunState 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/SendCarRunStateRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/SendCarRunStateResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateResponse SendCarRunState(CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateRequest request);
        
        // CODEGEN: 命名空间  的元素名称 CarRunStateSet 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetCarRunStateRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/GetCarRunStateResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateResponse GetCarRunState(CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateRequest request);
        
        // CODEGEN: 命名空间  的元素名称 CarRunStateSet 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/PostListCarRunStateRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/PostListCarRunStateResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateResponse PostListCarRunState(CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateRequest request);
        
        // CODEGEN: 命名空间  的元素名称 SmartWarnSet 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jaxws2.vispectcloud.com/SmartCarCloudService/PostListSmartWarnRequest", ReplyAction="http://jaxws2.vispectcloud.com/SmartCarCloudService/PostListSmartWarnResponse")]
        CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnResponse PostListSmartWarn(CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGather", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetGatherRequestBody Body;
        
        public GetGatherRequest() {
        }
        
        public GetGatherRequest(CloudServiceHostApp.HNLYLGJ.GATE.GetGatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetGatherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OptCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GatherList;
        
        public GetGatherRequestBody() {
        }
        
        public GetGatherRequestBody(string OptCode, int FlagCode, string GatherList) {
            this.OptCode = OptCode;
            this.FlagCode = FlagCode;
            this.GatherList = GatherList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGatherResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetGatherResponseBody Body;
        
        public GetGatherResponse() {
        }
        
        public GetGatherResponse(CloudServiceHostApp.HNLYLGJ.GATE.GetGatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetGatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GatherList;
        
        public GetGatherResponseBody() {
        }
        
        public GetGatherResponseBody(int @return, string GatherList) {
            this.@return = @return;
            this.GatherList = GatherList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BindingDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BindingDevice", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceRequestBody Body;
        
        public BindingDeviceRequest() {
        }
        
        public BindingDeviceRequest(CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class BindingDeviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AccountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CarID;
        
        public BindingDeviceRequestBody() {
        }
        
        public BindingDeviceRequestBody(string AccountID, string DeviceID, string CarID) {
            this.AccountID = AccountID;
            this.DeviceID = DeviceID;
            this.CarID = CarID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BindingDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BindingDeviceResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceResponseBody Body;
        
        public BindingDeviceResponse() {
        }
        
        public BindingDeviceResponse(CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class BindingDeviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public BindingDeviceResponseBody() {
        }
        
        public BindingDeviceResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmartWarnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmartWarn", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnRequestBody Body;
        
        public GetSmartWarnRequest() {
        }
        
        public GetSmartWarnRequest(CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetSmartWarnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OptCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SmartWarnList;
        
        public GetSmartWarnRequestBody() {
        }
        
        public GetSmartWarnRequestBody(string OptCode, int FlagCode, string SmartWarnList) {
            this.OptCode = OptCode;
            this.FlagCode = FlagCode;
            this.SmartWarnList = SmartWarnList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmartWarnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmartWarnResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnResponseBody Body;
        
        public GetSmartWarnResponse() {
        }
        
        public GetSmartWarnResponse(CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetSmartWarnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SmartWarnList;
        
        public GetSmartWarnResponseBody() {
        }
        
        public GetSmartWarnResponseBody(int @return, string SmartWarnList) {
            this.@return = @return;
            this.SmartWarnList = SmartWarnList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmartWarnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmartWarn", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnRequestBody Body;
        
        public SendSmartWarnRequest() {
        }
        
        public SendSmartWarnRequest(CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendSmartWarnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SmartWarn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        public SendSmartWarnRequestBody() {
        }
        
        public SendSmartWarnRequestBody(string SmartWarn, int FlagCode) {
            this.SmartWarn = SmartWarn;
            this.FlagCode = FlagCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmartWarnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmartWarnResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnResponseBody Body;
        
        public SendSmartWarnResponse() {
        }
        
        public SendSmartWarnResponse(CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendSmartWarnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public SendSmartWarnResponseBody() {
        }
        
        public SendSmartWarnResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgent", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetAgentRequestBody Body;
        
        public GetAgentRequest() {
        }
        
        public GetAgentRequest(CloudServiceHostApp.HNLYLGJ.GATE.GetAgentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetAgentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OptCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AgentList;
        
        public GetAgentRequestBody() {
        }
        
        public GetAgentRequestBody(string OptCode, int FlagCode, string AgentList) {
            this.OptCode = OptCode;
            this.FlagCode = FlagCode;
            this.AgentList = AgentList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAgentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAgentResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetAgentResponseBody Body;
        
        public GetAgentResponse() {
        }
        
        public GetAgentResponse(CloudServiceHostApp.HNLYLGJ.GATE.GetAgentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetAgentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AgentList;
        
        public GetAgentResponseBody() {
        }
        
        public GetAgentResponseBody(int @return, string AgentList) {
            this.@return = @return;
            this.AgentList = AgentList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterAccount", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountRequestBody Body;
        
        public RegisterAccountRequest() {
        }
        
        public RegisterAccountRequest(CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RegisterAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountID;
        
        public RegisterAccountRequestBody() {
        }
        
        public RegisterAccountRequestBody(string LoginName, string PassWord, string AccountID) {
            this.LoginName = LoginName;
            this.PassWord = PassWord;
            this.AccountID = AccountID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterAccountResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountResponseBody Body;
        
        public RegisterAccountResponse() {
        }
        
        public RegisterAccountResponse(CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RegisterAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountID;
        
        public RegisterAccountResponseBody() {
        }
        
        public RegisterAccountResponseBody(int @return, string AccountID) {
            this.@return = @return;
            this.AccountID = AccountID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccount", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetAccountRequestBody Body;
        
        public GetAccountRequest() {
        }
        
        public GetAccountRequest(CloudServiceHostApp.HNLYLGJ.GATE.GetAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OptCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountList;
        
        public GetAccountRequestBody() {
        }
        
        public GetAccountRequestBody(string OptCode, int FlagCode, string AccountList) {
            this.OptCode = OptCode;
            this.FlagCode = FlagCode;
            this.AccountList = AccountList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetAccountResponseBody Body;
        
        public GetAccountResponse() {
        }
        
        public GetAccountResponse(CloudServiceHostApp.HNLYLGJ.GATE.GetAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountList;
        
        public GetAccountResponseBody() {
        }
        
        public GetAccountResponseBody(int @return, string AccountList) {
            this.@return = @return;
            this.AccountList = AccountList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCloudRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCloud", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudRequestBody Body;
        
        public LoginCloudRequest() {
        }
        
        public LoginCloudRequest(CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginCloudRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountID;
        
        public LoginCloudRequestBody() {
        }
        
        public LoginCloudRequestBody(string LoginName, string PassWord, string AccountID) {
            this.LoginName = LoginName;
            this.PassWord = PassWord;
            this.AccountID = AccountID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginCloudResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginCloudResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudResponseBody Body;
        
        public LoginCloudResponse() {
        }
        
        public LoginCloudResponse(CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginCloudResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountID;
        
        public LoginCloudResponseBody() {
        }
        
        public LoginCloudResponseBody(int @return, string AccountID) {
            this.@return = @return;
            this.AccountID = AccountID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TotalSmartWarnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TotalSmartWarn", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnRequestBody Body;
        
        public TotalSmartWarnRequest() {
        }
        
        public TotalSmartWarnRequest(CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class TotalSmartWarnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OptCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TotalSmartWarn;
        
        public TotalSmartWarnRequestBody() {
        }
        
        public TotalSmartWarnRequestBody(string OptCode, int FlagCode, string TotalSmartWarn) {
            this.OptCode = OptCode;
            this.FlagCode = FlagCode;
            this.TotalSmartWarn = TotalSmartWarn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TotalSmartWarnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TotalSmartWarnResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnResponseBody Body;
        
        public TotalSmartWarnResponse() {
        }
        
        public TotalSmartWarnResponse(CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class TotalSmartWarnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TotalSmartWarn;
        
        public TotalSmartWarnResponseBody() {
        }
        
        public TotalSmartWarnResponseBody(int @return, string TotalSmartWarn) {
            this.@return = @return;
            this.TotalSmartWarn = TotalSmartWarn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthLogin", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginRequestBody Body;
        
        public AuthLoginRequest() {
        }
        
        public AuthLoginRequest(CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AuthLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountID;
        
        public AuthLoginRequestBody() {
        }
        
        public AuthLoginRequestBody(string LoginName, string PassWord, string AccountID) {
            this.LoginName = LoginName;
            this.PassWord = PassWord;
            this.AccountID = AccountID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthLoginResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginResponseBody Body;
        
        public AuthLoginResponse() {
        }
        
        public AuthLoginResponse(CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AuthLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountID;
        
        public AuthLoginResponseBody() {
        }
        
        public AuthLoginResponseBody(int @return, string AccountID) {
            this.@return = @return;
            this.AccountID = AccountID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCarRunStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCarRunState", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateRequestBody Body;
        
        public SendCarRunStateRequest() {
        }
        
        public SendCarRunStateRequest(CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendCarRunStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CarRunState;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        public SendCarRunStateRequestBody() {
        }
        
        public SendCarRunStateRequestBody(string CarRunState, int FlagCode) {
            this.CarRunState = CarRunState;
            this.FlagCode = FlagCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCarRunStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCarRunStateResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateResponseBody Body;
        
        public SendCarRunStateResponse() {
        }
        
        public SendCarRunStateResponse(CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendCarRunStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public SendCarRunStateResponseBody() {
        }
        
        public SendCarRunStateResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarRunStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarRunState", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateRequestBody Body;
        
        public GetCarRunStateRequest() {
        }
        
        public GetCarRunStateRequest(CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetCarRunStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CarRunStateSet;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CarRunStateList;
        
        public GetCarRunStateRequestBody() {
        }
        
        public GetCarRunStateRequestBody(string CarRunStateSet, int FlagCode, string CarRunStateList) {
            this.CarRunStateSet = CarRunStateSet;
            this.FlagCode = FlagCode;
            this.CarRunStateList = CarRunStateList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarRunStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarRunStateResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateResponseBody Body;
        
        public GetCarRunStateResponse() {
        }
        
        public GetCarRunStateResponse(CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetCarRunStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CarRunStateList;
        
        public GetCarRunStateResponseBody() {
        }
        
        public GetCarRunStateResponseBody(int @return, string CarRunStateList) {
            this.@return = @return;
            this.CarRunStateList = CarRunStateList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostListCarRunStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostListCarRunState", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateRequestBody Body;
        
        public PostListCarRunStateRequest() {
        }
        
        public PostListCarRunStateRequest(CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class PostListCarRunStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CarRunStateSet;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        public PostListCarRunStateRequestBody() {
        }
        
        public PostListCarRunStateRequestBody(string CarRunStateSet, int FlagCode) {
            this.CarRunStateSet = CarRunStateSet;
            this.FlagCode = FlagCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostListCarRunStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostListCarRunStateResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateResponseBody Body;
        
        public PostListCarRunStateResponse() {
        }
        
        public PostListCarRunStateResponse(CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class PostListCarRunStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        public PostListCarRunStateResponseBody() {
        }
        
        public PostListCarRunStateResponseBody(int @return, int FlagCode) {
            this.@return = @return;
            this.FlagCode = FlagCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostListSmartWarnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostListSmartWarn", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnRequestBody Body;
        
        public PostListSmartWarnRequest() {
        }
        
        public PostListSmartWarnRequest(CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class PostListSmartWarnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SmartWarnSet;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        public PostListSmartWarnRequestBody() {
        }
        
        public PostListSmartWarnRequestBody(string SmartWarnSet, int FlagCode) {
            this.SmartWarnSet = SmartWarnSet;
            this.FlagCode = FlagCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostListSmartWarnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostListSmartWarnResponse", Namespace="http://jaxws2.vispectcloud.com/", Order=0)]
        public CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnResponseBody Body;
        
        public PostListSmartWarnResponse() {
        }
        
        public PostListSmartWarnResponse(CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class PostListSmartWarnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FlagCode;
        
        public PostListSmartWarnResponseBody() {
        }
        
        public PostListSmartWarnResponseBody(int @return, int FlagCode) {
            this.@return = @return;
            this.FlagCode = FlagCode;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmartCarCloudServiceChannel : CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartCarCloudServiceClient : System.ServiceModel.ClientBase<CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService>, CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService {
        
        public SmartCarCloudServiceClient() {
        }
        
        public SmartCarCloudServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartCarCloudServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartCarCloudServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartCarCloudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.GetGatherResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.GetGather(CloudServiceHostApp.HNLYLGJ.GATE.GetGatherRequest request) {
            return base.Channel.GetGather(request);
        }
        
        public int GetGather(string OptCode, int FlagCode, ref string GatherList) {
            CloudServiceHostApp.HNLYLGJ.GATE.GetGatherRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.GetGatherRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.GetGatherRequestBody();
            inValue.Body.OptCode = OptCode;
            inValue.Body.FlagCode = FlagCode;
            inValue.Body.GatherList = GatherList;
            CloudServiceHostApp.HNLYLGJ.GATE.GetGatherResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).GetGather(inValue);
            GatherList = retVal.Body.GatherList;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.BindingDevice(CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceRequest request) {
            return base.Channel.BindingDevice(request);
        }
        
        public int BindingDevice(string AccountID, string DeviceID, string CarID) {
            CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceRequestBody();
            inValue.Body.AccountID = AccountID;
            inValue.Body.DeviceID = DeviceID;
            inValue.Body.CarID = CarID;
            CloudServiceHostApp.HNLYLGJ.GATE.BindingDeviceResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).BindingDevice(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.GetSmartWarn(CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnRequest request) {
            return base.Channel.GetSmartWarn(request);
        }
        
        public int GetSmartWarn(string OptCode, int FlagCode, ref string SmartWarnList) {
            CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnRequestBody();
            inValue.Body.OptCode = OptCode;
            inValue.Body.FlagCode = FlagCode;
            inValue.Body.SmartWarnList = SmartWarnList;
            CloudServiceHostApp.HNLYLGJ.GATE.GetSmartWarnResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).GetSmartWarn(inValue);
            SmartWarnList = retVal.Body.SmartWarnList;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.SendSmartWarn(CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnRequest request) {
            return base.Channel.SendSmartWarn(request);
        }
        
        public int SendSmartWarn(string SmartWarn, int FlagCode) {
            CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnRequestBody();
            inValue.Body.SmartWarn = SmartWarn;
            inValue.Body.FlagCode = FlagCode;
            CloudServiceHostApp.HNLYLGJ.GATE.SendSmartWarnResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).SendSmartWarn(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.GetAgentResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.GetAgent(CloudServiceHostApp.HNLYLGJ.GATE.GetAgentRequest request) {
            return base.Channel.GetAgent(request);
        }
        
        public int GetAgent(string OptCode, int FlagCode, ref string AgentList) {
            CloudServiceHostApp.HNLYLGJ.GATE.GetAgentRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.GetAgentRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.GetAgentRequestBody();
            inValue.Body.OptCode = OptCode;
            inValue.Body.FlagCode = FlagCode;
            inValue.Body.AgentList = AgentList;
            CloudServiceHostApp.HNLYLGJ.GATE.GetAgentResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).GetAgent(inValue);
            AgentList = retVal.Body.AgentList;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.RegisterAccount(CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountRequest request) {
            return base.Channel.RegisterAccount(request);
        }
        
        public int RegisterAccount(string LoginName, string PassWord, ref string AccountID) {
            CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountRequestBody();
            inValue.Body.LoginName = LoginName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.AccountID = AccountID;
            CloudServiceHostApp.HNLYLGJ.GATE.RegisterAccountResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).RegisterAccount(inValue);
            AccountID = retVal.Body.AccountID;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.GetAccountResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.GetAccount(CloudServiceHostApp.HNLYLGJ.GATE.GetAccountRequest request) {
            return base.Channel.GetAccount(request);
        }
        
        public int GetAccount(string OptCode, int FlagCode, ref string AccountList) {
            CloudServiceHostApp.HNLYLGJ.GATE.GetAccountRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.GetAccountRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.GetAccountRequestBody();
            inValue.Body.OptCode = OptCode;
            inValue.Body.FlagCode = FlagCode;
            inValue.Body.AccountList = AccountList;
            CloudServiceHostApp.HNLYLGJ.GATE.GetAccountResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).GetAccount(inValue);
            AccountList = retVal.Body.AccountList;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.LoginCloud(CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudRequest request) {
            return base.Channel.LoginCloud(request);
        }
        
        public int LoginCloud(string LoginName, string PassWord, ref string AccountID) {
            CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudRequestBody();
            inValue.Body.LoginName = LoginName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.AccountID = AccountID;
            CloudServiceHostApp.HNLYLGJ.GATE.LoginCloudResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).LoginCloud(inValue);
            AccountID = retVal.Body.AccountID;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.TotalSmartWarn(CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnRequest request) {
            return base.Channel.TotalSmartWarn(request);
        }
        
        public int TotalSmartWarn(string OptCode, int FlagCode, string TotalSmartWarn1, out string TotalSmartWarn2) {
            CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnRequestBody();
            inValue.Body.OptCode = OptCode;
            inValue.Body.FlagCode = FlagCode;
            inValue.Body.TotalSmartWarn = TotalSmartWarn1;
            CloudServiceHostApp.HNLYLGJ.GATE.TotalSmartWarnResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).TotalSmartWarn(inValue);
            TotalSmartWarn2 = retVal.Body.TotalSmartWarn;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.AuthLogin(CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginRequest request) {
            return base.Channel.AuthLogin(request);
        }
        
        public int AuthLogin(string LoginName, string PassWord, ref string AccountID) {
            CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginRequestBody();
            inValue.Body.LoginName = LoginName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.AccountID = AccountID;
            CloudServiceHostApp.HNLYLGJ.GATE.AuthLoginResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).AuthLogin(inValue);
            AccountID = retVal.Body.AccountID;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.SendCarRunState(CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateRequest request) {
            return base.Channel.SendCarRunState(request);
        }
        
        public int SendCarRunState(string CarRunState, int FlagCode) {
            CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateRequestBody();
            inValue.Body.CarRunState = CarRunState;
            inValue.Body.FlagCode = FlagCode;
            CloudServiceHostApp.HNLYLGJ.GATE.SendCarRunStateResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).SendCarRunState(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.GetCarRunState(CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateRequest request) {
            return base.Channel.GetCarRunState(request);
        }
        
        public int GetCarRunState(string CarRunStateSet, int FlagCode, ref string CarRunStateList) {
            CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateRequestBody();
            inValue.Body.CarRunStateSet = CarRunStateSet;
            inValue.Body.FlagCode = FlagCode;
            inValue.Body.CarRunStateList = CarRunStateList;
            CloudServiceHostApp.HNLYLGJ.GATE.GetCarRunStateResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).GetCarRunState(inValue);
            CarRunStateList = retVal.Body.CarRunStateList;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.PostListCarRunState(CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateRequest request) {
            return base.Channel.PostListCarRunState(request);
        }
        
        public int PostListCarRunState(string CarRunStateSet, ref int FlagCode) {
            CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateRequestBody();
            inValue.Body.CarRunStateSet = CarRunStateSet;
            inValue.Body.FlagCode = FlagCode;
            CloudServiceHostApp.HNLYLGJ.GATE.PostListCarRunStateResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).PostListCarRunState(inValue);
            FlagCode = retVal.Body.FlagCode;
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnResponse CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService.PostListSmartWarn(CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnRequest request) {
            return base.Channel.PostListSmartWarn(request);
        }
        
        public int PostListSmartWarn(string SmartWarnSet, ref int FlagCode) {
            CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnRequest inValue = new CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnRequest();
            inValue.Body = new CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnRequestBody();
            inValue.Body.SmartWarnSet = SmartWarnSet;
            inValue.Body.FlagCode = FlagCode;
            CloudServiceHostApp.HNLYLGJ.GATE.PostListSmartWarnResponse retVal = ((CloudServiceHostApp.HNLYLGJ.GATE.SmartCarCloudService)(this)).PostListSmartWarn(inValue);
            FlagCode = retVal.Body.FlagCode;
            return retVal.Body.@return;
        }
    }
}
